version: '3.8'
services:
  frontend:
    build:
      context: ./my-app
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./myapp-backend/MyApi
      dockerfile: ../Dockerfile
    ports:
      - "5189:5189"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
